=== LatiosJet/VolPhotonMapper/src/dist/renderground-scene-schema.json
{
    "$id": "renderground.scene.schema.json",
    "$schema": "http://json-schema.org/draft-04/schema",
    "description": "Renderground scene file",
    "type": "object",

    "properties": {
        "name": {},
        "transforms": {},
        "cameras": {},
        "materials": {},
        "objects": {}
    },

    "definitions": {

    }
}

=== LatiosJet/VolPhotonMapper/SeeSharp.Templates/content/SeeSharp.Template/Scenes/ExampleScene/ExampleScene.json
{
  "materials": [
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          1.0,
          1.0,
          1.0
        ]
      },
      "roughness": 1.0,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.4500000476837158,
      "metallic": 0.0,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "Dots Stroke"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          0.8431711196899414,
          0.7955026626586914,
          0.7034096717834473
        ]
      },
      "roughness": 1.0,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.580434799194336,
      "metallic": 0.0,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "Floor"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          1.0,
          1.0,
          1.0
        ]
      },
      "roughness": 1.0,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.4500000476837158,
      "metallic": 0.0,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "FrontWall"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          0.01695714332163334,
          0.02009124681353569,
          0.021581411361694336
        ]
      },
      "roughness": 0.18478262424468994,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.4500000476837158,
      "metallic": 0.782608687877655,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "LampCord"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          0.5240858793258667,
          0.5479063987731934,
          0.5901280641555786
        ]
      },
      "roughness": 0.11956518888473511,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.3195652961730957,
      "metallic": 0.907608687877655,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "LampShade"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          0.11181189119815826,
          0.4437788128852844,
          0.6444829106330872
        ]
      },
      "roughness": 1.0,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.2978261709213257,
      "metallic": 0.0,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "LeftWall"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "roughness": 1.0,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.4500000476837158,
      "metallic": 0.0,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          1000.0,
          871.5412020683289,
          627.8089284896851
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "LightBulb"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          0.8063408136367798,
          0.31818580627441406,
          0.04331871494650841
        ]
      },
      "roughness": 1.0,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.2760870456695557,
      "metallic": 0.0,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "RightWall"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          0.5242688655853271,
          0.39161431789398193,
          0.06801436096429825
        ]
      },
      "roughness": 0.04347825050354004,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.4500000476837158,
      "metallic": 1.0,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "Ring"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          1.0,
          1.0,
          1.0
        ]
      },
      "roughness": 1.0,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.4500000476837158,
      "metallic": 0.0,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "Roof"
    },
    {
      "type": "generic",
      "baseColor": {
        "type": "rgb",
        "value": [
          0.6526120901107788,
          0.20355242490768433,
          0.06327579915523529
        ]
      },
      "roughness": 0.907608687877655,
      "anisotropic": 0.0,
      "diffuseTransmittance": 0.0,
      "IOR": 1.286956548690796,
      "metallic": 0.1875,
      "specularTintStrength": 0.0,
      "specularTransmittance": 0.0,
      "thin": false,
      "emission": {
        "type": "rgb",
        "value": [
          0.0,
          0.0,
          0.0
        ]
      },
      "emissionIsGlossy": false,
      "emissionExponent": 20.0,
      "name": "Suzanne"
    }
  ],
  "transforms": [
    {
      "name": "camera",
      "position": [
        -7.381510257720947,
        2.691025495529175,
        -5.706736087799072
      ],
      "rotation": [
        -5.60854586077528,
        231.31159806423486,
        -0.00035797836860570066
      ],
      "scale": [
        1.0,
        1.0,
        1.0
      ]
    }
  ],
  "cameras": [
    {
      "fov": 23.142760200926997,
      "transform": "camera",
      "name": "default",
      "type": "perspective"
    }
  ],
  "objects": [
    {
      "name": "Floor",
      "type": "ply",
      "material": "Floor",
      "relativePath": "Meshes/Floor.0.ply"
    },
    {
      "name": "Suzanne",
      "type": "ply",
      "material": "Suzanne",
      "relativePath": "Meshes/Suzanne.0.ply"
    },
    {
      "name": "RightWall",
      "type": "ply",
      "material": "RightWall",
      "relativePath": "Meshes/RightWall.0.ply"
    },
    {
      "name": "LeftWall",
      "type": "ply",
      "material": "LeftWall",
      "relativePath": "Meshes/LeftWall.0.ply"
    },
    {
      "name": "FrontWall",
      "type": "ply",
      "material": "FrontWall",
      "relativePath": "Meshes/FrontWall.0.ply"
    },
    {
      "name": "LightBulb",
      "type": "ply",
      "material": "LightBulb",
      "relativePath": "Meshes/LightBulb.0.ply"
    },
    {
      "name": "LampShade",
      "type": "ply",
      "material": "LampShade",
      "relativePath": "Meshes/LampShade.0.ply"
    },
    {
      "name": "Roof",
      "type": "ply",
      "material": "Roof",
      "relativePath": "Meshes/Roof.0.ply"
    },
    {
      "name": "LampCord",
      "type": "ply",
      "material": "LampCord",
      "relativePath": "Meshes/LampCord.0.ply"
    },
    {
      "name": "Ring",
      "type": "ply",
      "material": "Ring",
      "relativePath": "Meshes/Ring.0.ply"
    }
  ]
}

=== LatiosJet/VolPhotonMapper/Data/Scenes/TextureTest/TextureTest.json
{
  "materials": [
    {
      "type": "diffuse",
      "baseColor": {
        "type": "rgb",
        "value": [
          0.800000011920929,
          0.800000011920929,
          0.800000011920929
        ]
      },
      "name": "Dots_Stroke"
    },
    {
      "type": "diffuse",
      "baseColor": {
        "type": "rgb",
        "value": [
          0,
          0,
          0
        ]
      },
      "emission": {
        "type": "rgb",
        "value": [
          10.0,
          10.0,
          10.0
        ]
      },
      "name": "Material.001"
    },
    {
      "type": "diffuse",
      "baseColor": {
        "type": "image",
        "filename": "Textures/TestPattern.png"
      },
      "name": "Material.002"
    }
  ],
  "transforms": [
    {
      "name": "camera",
      "position": [
        0.05385369062423706,
        5.471238613128662,
        -0.059679657220840454
      ],
      "rotation": [
        -89.45677456474138,
        179.8844821311455,
        0.4280197540739464
      ],
      "scale": [
        1.0,
        1.0,
        1.0
      ]
    }
  ],
  "cameras": [
    {
      "fov": 22.895194130645738,
      "transform": "camera",
      "name": "default",
      "type": "perspective"
    }
  ],
  "objects": [
    {
      "name": "scene",
      "type": "obj",
      "relativePath": "TextureTest.obj"
    }
  ]
}

=== LatiosJet/VolPhotonMapper/data/scenes/furnacebox.json
{
    "name": "Cornell Box",
    "transforms": [
      {
        "name": "camera",
        "position": [ 0.0, 1.0, 6.8 ],
        "rotation": [ 0, 180.0, 180.0 ],
        "scale": [ -1.0, 1.0, 1.0 ]
      }
    ],
    "cameras": [
      {
        "name": "default",
        "type": "perspective",
        "fov": 19.5,
        "transform": "camera"
      }
    ],
    "materials": [
      {
        "name": "ShortBox",
        "baseColor": {
          "type": "rgb",
          "value": [1, 1, 1]
        }
      }
    ],
    "objects": [
      {
        "name": "mesh6",
        "material": "ShortBox",
        "type": "trimesh",
        "indices": [
          0,
          2,
          1,
          0,
          3,
          2,
          4,
          6,
          5,
          4,
          7,
          6,
          8,
          10,
          9,
          8,
          11,
          10,
          12,
          14,
          13,
          12,
          15,
          14,
          16,
          18,
          17,
          16,
          19,
          18,
          20,
          22,
          21,
          20,
          23,
          22
        ],
        "vertices": [
          -0.0460751, 0.6, 0.573007,
          -0.0460751, -2.98023e-08, 0.573007,
          0.124253, 0.0, 0.00310463,
          0.124253, 0.6, 0.00310463,
          0.533009, 0.0, 0.746079,
          0.533009, 0.6, 0.746079,
          0.703337, 0.6, 0.176177,
          0.703337, 2.98023e-08, 0.176177,
          0.533009, 0.6, 0.746079,
          -0.0460751, 0.6, 0.573007,
          0.124253, 0.6, 0.00310463,
          0.703337, 0.6, 0.176177,
          0.703337, 2.98023e-08, 0.176177,
          0.124253, 0.0, 0.00310463,
          -0.0460751, -2.98023e-08, 0.573007,
          0.533009, 0.0, 0.746079,
          0.533009, 0.0, 0.746079,
          -0.0460751, -2.98023e-08, 0.573007,
          -0.0460751, 0.6, 0.573007,
          0.533009, 0.6, 0.746079,
          0.703337, 0.6, 0.176177,
          0.124253, 0.6, 0.00310463,
          0.124253, 0.0, 0.00310463,
          0.703337, 2.98023e-08, 0.176177
        ],
        "normals": [
          -0.958123, -4.18809e-08, -0.286357,
          -0.958123, -4.18809e-08, -0.286357,
          -0.958123, -4.18809e-08, -0.286357,
          -0.958123, -4.18809e-08, -0.286357,
          0.958123, 4.18809e-08, 0.286357,
          0.958123, 4.18809e-08, 0.286357,
          0.958123, 4.18809e-08, 0.286357,
          0.958123, 4.18809e-08, 0.286357,
          -4.37114e-08, 1.0, -1.91069e-15,
          -4.37114e-08, 1.0, -1.91069e-15,
          -4.37114e-08, 1.0, -1.91069e-15,
          -4.37114e-08, 1.0, -1.91069e-15,
          4.37114e-08, -1.0, 1.91069e-15,
          4.37114e-08, -1.0, 1.91069e-15,
          4.37114e-08, -1.0, 1.91069e-15,
          4.37114e-08, -1.0, 1.91069e-15,
          -0.286357, -1.25171e-08, 0.958123,
          -0.286357, -1.25171e-08, 0.958123,
          -0.286357, -1.25171e-08, 0.958123,
          -0.286357, -1.25171e-08, 0.958123,
          0.286357, 1.25171e-08, -0.958123,
          0.286357, 1.25171e-08, -0.958123,
          0.286357, 1.25171e-08, -0.958123,
          0.286357, 1.25171e-08, -0.958123
        ],
        "uv": [
          0.0,
          0.0,
          1.0,
          0.0,
          1.0,
          1.0,
          0.0,
          1.0,
          0.0,
          0.0,
          1.0,
          0.0,
          1.0,
          1.0,
          0.0,
          1.0,
          0.0,
          0.0,
          1.0,
          0.0,
          1.0,
          1.0,
          0.0,
          1.0,
          0.0,
          0.0,
          1.0,
          0.0,
          1.0,
          1.0,
          0.0,
          1.0,
          0.0,
          0.0,
          1.0,
          0.0,
          1.0,
          1.0,
          0.0,
          1.0,
          0.0,
          0.0,
          1.0,
          0.0,
          1.0,
          1.0,
          0.0,
          1.0
        ]
      }
    ]
  }

=== LatiosJet/VolPhotonMapper/data/scenes/simpledi.json
{
    "name": "Simple direct illumination",
    "transforms": [
      {
        "name": "camera",
        "position": [ 0, 1.8, 0 ],
        "rotation": [ 90, 0, 0 ],
        "scale": [ 1, 1, 1 ]
      }
    ],
    "cameras": [
      {
        "name": "default",
        "type": "perspective",
        "fov": 19.5,
        "transform": "camera"
      }
    ],
    "materials": [
      {
        "name": "Quad",
        "baseColor": {
          "type": "rgb",
          "value": [1, 1, 1]
        }
      },
      {
        "name": "Light",
        "baseColor": {
          "type": "rgb",
          "value": [ 0, 0, 0 ]
        }
      }
    ],
    "objects": [
      {
        "name": "light",
        "emission": {
          "type": "rgb",
          "unit": "radiance",
          "value": [20.0, 20.0, 20.0]
        },
        "material": "Light",
        "type": "trimesh",
        "indices": [
          0, 1, 2,
          0, 2, 3
        ],
        "vertices": [
          -0.2, 2.0, -0.2,
           0.2, 2.0, -0.2,
           0.2, 2.0,  0.2,
          -0.2, 2.0,  0.2
        ],
        "normals": [
          0, -1, 0,
          0, -1, 0,
          0, -1, 0,
          0, -1, 0
        ],
        "uv": [
          0.0, 0.0,
          1.0, 0.0,
          1.0, 1.0,
          0.0, 1.0
        ]
      },
      {
        "name": "quad",
        "material": "Quad",
        "type": "trimesh",
        "indices": [
          0, 2, 1,
          0, 3, 2
        ],
        "vertices": [
          -10.0, 0.0, -10.0,
           10.0, 0.0, -10.0,
           10.0, 0.0,  10.0,
          -10.0, 0.0,  10.0
        ],
        "normals": [
          0, -1, 0,
          0, -1, 0,
          0, -1, 0,
          0, -1, 0
        ],
        "uv": [
          0.0, 0.0,
          1.0, 0.0,
          1.0, 1.0,
          0.0, 1.0
        ]
      }
    ]
  }
